### ISSUE TITLE
Only works with GridLayout??

### ISSUE THREAD

**Issue by csbenz** [AndroidDeveloperLB/FastScrollerAndRecyclerViewFixes#3]
```
java.lang.ClassCastException: androidx.recyclerview.widget.LinearLayoutManager cannot be cast to androidx.recyclerview.widget.GridLayoutManager
                                                                                                    	at com.lb.fast_scroller_and_recycler_view_fixes_library.GridLayoutManagerUtils.getLastItemPositionOnSameRow(GridLayoutManagerUtils.kt:37)
                                                                                                    	at com.lb.fast_scroller_and_recycler_view_fixes_library.GridLayoutManagerUtils.isOnLastRow(GridLayoutManagerUtils.kt:27)
                                                                                                    	at com.lb.fast_scroller_and_recycler_view_fixes_library.BottomOffsetDecoration.getItemOffsets(BottomOffsetDecoration.kt:28)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView.getItemDecorInsetsForChild(RecyclerView.java:5634)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView$LayoutManager.measureChildWithMargins(RecyclerView.java:10197)
                                                                                                    	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1688)
                                                                                                    	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
                                                                                                    	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:687)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4645)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4348)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4919)
                                                                                                    	at android.view.View.layout(View.java:24527)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6455)
                                                                                                    	at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:149)
                                                                                                    	at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
                                                                                                    	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:2365)
                                                                                                    	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
                                                                                                    	at android.view.View.layout(View.java:24527)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6455)
                                                                                                    	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
                                                                                                    	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
                                                                                                    	at android.view.View.layout(View.java:24527)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6455)
                                                                                                    	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
                                                                                                    	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
                                                                                                    	at android.view.View.layout(View.java:24527)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6455)
                                                                                                    	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
                                                                                                    	at android.view.View.layout(View.java:24527)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6455)
                                                                                                    	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
                                                                                                    	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
                                                                                                    	at android.view.View.layout(View.java:24527)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6455)
                                                                                                    	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:2004)
                                                                                                    	at android.view.View.layout(View.java:24527)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6455)
                                                                                                    	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
                                                                                                    	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
                                                                                                    	at android.view.View.layout(View.java:24527)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6455)
                                                                                                    	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
                                                                                                    	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
                                                                                                    	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
                                                                                                    	at android.view.View.layout(View.java:24527)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6455)
                                                                                                    	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
                                                                                                    	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
                                                                                                    	at android.view.View.layout(View.java:24527)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6455)
                                                                                                    	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
                                                                                                    	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
                                                                                                    	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
2024-05-29 12:31:13.049  9670-9670  AndroidRuntime                            E  	at android.view.View.layout(View.java:24527)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6455)
                                                                                                    	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
                                                                                                    	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
                                                                                                    	at com.android.internal.policy.DecorView.onLayout(DecorView.java:810)
                                                                                                    	at android.view.View.layout(View.java:24527)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6455)
                                                                                                    	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4553)
                                                                                                    	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3859)
                                                                                                    	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2687)
                                                                                                    	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9776)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1343)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1352)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:952)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:882)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1326)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:1000)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:242)
                                                                                                    	at android.os.Looper.loop(Looper.java:362)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8407)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992)
```

**Comment by AndroidDeveloperLB** [comment]
What is this?
